# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.models.docx_table_row import DocxTableRow  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestDocxTableRow(unittest.TestCase):
    """DocxTableRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocxTableRow(self):
        """Test DocxTableRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_convert_api_client.models.docx_table_row.DocxTableRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
