# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.models.find_regex_match import FindRegexMatch  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestFindRegexMatch(unittest.TestCase):
    """FindRegexMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindRegexMatch(self):
        """Test FindRegexMatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_convert_api_client.models.find_regex_match.FindRegexMatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
