# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.models.insert_docx_comment_on_paragraph_response import InsertDocxCommentOnParagraphResponse  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestInsertDocxCommentOnParagraphResponse(unittest.TestCase):
    """InsertDocxCommentOnParagraphResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsertDocxCommentOnParagraphResponse(self):
        """Test InsertDocxCommentOnParagraphResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_convert_api_client.models.insert_docx_comment_on_paragraph_response.InsertDocxCommentOnParagraphResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
