# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.models.get_xlsx_rows_and_cells_response import GetXlsxRowsAndCellsResponse  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestGetXlsxRowsAndCellsResponse(unittest.TestCase):
    """GetXlsxRowsAndCellsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetXlsxRowsAndCellsResponse(self):
        """Test GetXlsxRowsAndCellsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_convert_api_client.models.get_xlsx_rows_and_cells_response.GetXlsxRowsAndCellsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
