# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.models.delete_docx_table_row_response import DeleteDocxTableRowResponse  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestDeleteDocxTableRowResponse(unittest.TestCase):
    """DeleteDocxTableRowResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteDocxTableRowResponse(self):
        """Test DeleteDocxTableRowResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_convert_api_client.models.delete_docx_table_row_response.DeleteDocxTableRowResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
