# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.api.convert_image_api import ConvertImageApi  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestConvertImageApi(unittest.TestCase):
    """ConvertImageApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_convert_api_client.api.convert_image_api.ConvertImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_image_image_format_convert(self):
        """Test case for convert_image_image_format_convert

        Image format conversion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
