# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_convert_api_client
from cloudmersive_convert_api_client.models.converted_jpg_page import ConvertedJpgPage  # noqa: E501
from cloudmersive_convert_api_client.rest import ApiException


class TestConvertedJpgPage(unittest.TestCase):
    """ConvertedJpgPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConvertedJpgPage(self):
        """Test ConvertedJpgPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_convert_api_client.models.converted_jpg_page.ConvertedJpgPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
