# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocxFooter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'paragraphs': 'list[DocxParagraph]',
        'sections_with_footer': 'list[DocxSection]'
    }

    attribute_map = {
        'path': 'Path',
        'paragraphs': 'Paragraphs',
        'sections_with_footer': 'SectionsWithFooter'
    }

    def __init__(self, path=None, paragraphs=None, sections_with_footer=None):  # noqa: E501
        """DocxFooter - a model defined in Swagger"""  # noqa: E501

        self._path = None
        self._paragraphs = None
        self._sections_with_footer = None
        self.discriminator = None

        if path is not None:
            self.path = path
        if paragraphs is not None:
            self.paragraphs = paragraphs
        if sections_with_footer is not None:
            self.sections_with_footer = sections_with_footer

    @property
    def path(self):
        """Gets the path of this DocxFooter.  # noqa: E501

        The Path of the location of this object; leave blank for new tables  # noqa: E501

        :return: The path of this DocxFooter.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this DocxFooter.

        The Path of the location of this object; leave blank for new tables  # noqa: E501

        :param path: The path of this DocxFooter.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def paragraphs(self):
        """Gets the paragraphs of this DocxFooter.  # noqa: E501

        Paragraphs in this footer  # noqa: E501

        :return: The paragraphs of this DocxFooter.  # noqa: E501
        :rtype: list[DocxParagraph]
        """
        return self._paragraphs

    @paragraphs.setter
    def paragraphs(self, paragraphs):
        """Sets the paragraphs of this DocxFooter.

        Paragraphs in this footer  # noqa: E501

        :param paragraphs: The paragraphs of this DocxFooter.  # noqa: E501
        :type: list[DocxParagraph]
        """

        self._paragraphs = paragraphs

    @property
    def sections_with_footer(self):
        """Gets the sections_with_footer of this DocxFooter.  # noqa: E501

        Sections that the footer is applied to  # noqa: E501

        :return: The sections_with_footer of this DocxFooter.  # noqa: E501
        :rtype: list[DocxSection]
        """
        return self._sections_with_footer

    @sections_with_footer.setter
    def sections_with_footer(self, sections_with_footer):
        """Sets the sections_with_footer of this DocxFooter.

        Sections that the footer is applied to  # noqa: E501

        :param sections_with_footer: The sections_with_footer of this DocxFooter.  # noqa: E501
        :type: list[DocxSection]
        """

        self._sections_with_footer = sections_with_footer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocxFooter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocxFooter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
