# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetDocxCommentsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'successful': 'bool',
        'comments': 'list[DocxComment]',
        'comment_count': 'int'
    }

    attribute_map = {
        'successful': 'Successful',
        'comments': 'Comments',
        'comment_count': 'CommentCount'
    }

    def __init__(self, successful=None, comments=None, comment_count=None):  # noqa: E501
        """GetDocxCommentsResponse - a model defined in Swagger"""  # noqa: E501

        self._successful = None
        self._comments = None
        self._comment_count = None
        self.discriminator = None

        if successful is not None:
            self.successful = successful
        if comments is not None:
            self.comments = comments
        if comment_count is not None:
            self.comment_count = comment_count

    @property
    def successful(self):
        """Gets the successful of this GetDocxCommentsResponse.  # noqa: E501

        True if successful, false otherwise  # noqa: E501

        :return: The successful of this GetDocxCommentsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._successful

    @successful.setter
    def successful(self, successful):
        """Sets the successful of this GetDocxCommentsResponse.

        True if successful, false otherwise  # noqa: E501

        :param successful: The successful of this GetDocxCommentsResponse.  # noqa: E501
        :type: bool
        """

        self._successful = successful

    @property
    def comments(self):
        """Gets the comments of this GetDocxCommentsResponse.  # noqa: E501

        Comments in the document  # noqa: E501

        :return: The comments of this GetDocxCommentsResponse.  # noqa: E501
        :rtype: list[DocxComment]
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this GetDocxCommentsResponse.

        Comments in the document  # noqa: E501

        :param comments: The comments of this GetDocxCommentsResponse.  # noqa: E501
        :type: list[DocxComment]
        """

        self._comments = comments

    @property
    def comment_count(self):
        """Gets the comment_count of this GetDocxCommentsResponse.  # noqa: E501

        The number of comments in the document  # noqa: E501

        :return: The comment_count of this GetDocxCommentsResponse.  # noqa: E501
        :rtype: int
        """
        return self._comment_count

    @comment_count.setter
    def comment_count(self, comment_count):
        """Sets the comment_count of this GetDocxCommentsResponse.

        The number of comments in the document  # noqa: E501

        :param comment_count: The comment_count of this GetDocxCommentsResponse.  # noqa: E501
        :type: int
        """

        self._comment_count = comment_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetDocxCommentsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetDocxCommentsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
