# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PdfPageText(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'page_number': 'int',
        'page_text': 'str'
    }

    attribute_map = {
        'page_number': 'PageNumber',
        'page_text': 'PageText'
    }

    def __init__(self, page_number=None, page_text=None):  # noqa: E501
        """PdfPageText - a model defined in Swagger"""  # noqa: E501

        self._page_number = None
        self._page_text = None
        self.discriminator = None

        if page_number is not None:
            self.page_number = page_number
        if page_text is not None:
            self.page_text = page_text

    @property
    def page_number(self):
        """Gets the page_number of this PdfPageText.  # noqa: E501

        Page number of the page (1-based)  # noqa: E501

        :return: The page_number of this PdfPageText.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this PdfPageText.

        Page number of the page (1-based)  # noqa: E501

        :param page_number: The page_number of this PdfPageText.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def page_text(self):
        """Gets the page_text of this PdfPageText.  # noqa: E501

        Text of the page  # noqa: E501

        :return: The page_text of this PdfPageText.  # noqa: E501
        :rtype: str
        """
        return self._page_text

    @page_text.setter
    def page_text(self, page_text):
        """Sets the page_text of this PdfPageText.

        Text of the page  # noqa: E501

        :param page_text: The page_text of this PdfPageText.  # noqa: E501
        :type: str
        """

        self._page_text = page_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PdfPageText, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PdfPageText):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
