# coding: utf-8

"""
    convertapi

    Convert API lets you effortlessly convert file formats and types.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PptxSplitAdvancedRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_file': 'str',
        'slides_per_presentation': 'int'
    }

    attribute_map = {
        'input_file': 'InputFile',
        'slides_per_presentation': 'SlidesPerPresentation'
    }

    def __init__(self, input_file=None, slides_per_presentation=None):  # noqa: E501
        """PptxSplitAdvancedRequest - a model defined in Swagger"""  # noqa: E501

        self._input_file = None
        self._slides_per_presentation = None
        self.discriminator = None

        if input_file is not None:
            self.input_file = input_file
        if slides_per_presentation is not None:
            self.slides_per_presentation = slides_per_presentation

    @property
    def input_file(self):
        """Gets the input_file of this PptxSplitAdvancedRequest.  # noqa: E501

        Input file  # noqa: E501

        :return: The input_file of this PptxSplitAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file):
        """Sets the input_file of this PptxSplitAdvancedRequest.

        Input file  # noqa: E501

        :param input_file: The input_file of this PptxSplitAdvancedRequest.  # noqa: E501
        :type: str
        """
        if input_file is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', input_file):  # noqa: E501
            raise ValueError(r"Invalid value for `input_file`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._input_file = input_file

    @property
    def slides_per_presentation(self):
        """Gets the slides_per_presentation of this PptxSplitAdvancedRequest.  # noqa: E501

        Slides per presentation for result  # noqa: E501

        :return: The slides_per_presentation of this PptxSplitAdvancedRequest.  # noqa: E501
        :rtype: int
        """
        return self._slides_per_presentation

    @slides_per_presentation.setter
    def slides_per_presentation(self, slides_per_presentation):
        """Sets the slides_per_presentation of this PptxSplitAdvancedRequest.

        Slides per presentation for result  # noqa: E501

        :param slides_per_presentation: The slides_per_presentation of this PptxSplitAdvancedRequest.  # noqa: E501
        :type: int
        """

        self._slides_per_presentation = slides_per_presentation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PptxSplitAdvancedRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PptxSplitAdvancedRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
